apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-data
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume-type: nfs
      type: custom